name: ericlam
favicon: null
layout_spectrum: 0
typography_spectrum: 0.12876
title: I am a wannabe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9861774414312094
  lightness: 0.5129120068158954
  saturation: 0.6599447962362319
  rhythmicContrast: 0.25
purpose: []
